apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentication-user-management/delete-kubeadmin/template.yaml
- authentication-user-management/shorten-tokens/template.yaml
- authentication-user-management/oauth-secured-identity-providers-only/template.yaml
- authorization/disallow-privileged-scc-usage/template.yaml
- authorization/prevent-default-serviceaccount-usage/template.yaml
- etcd-security/verify-etcd-encryption/template.yaml
- networking/block-nodeport-services/template.yaml
- networking/external-ips/template.yaml
- networking/httpsonly/template.yaml
- resource-exhaustion/disallow-self-provisioner/template.yaml
- trusted-image-sources/disallowedtags/template.yaml
- authorization/disallow-host-network/template.yaml
- authorization/disallow-host-namespaces/template.yaml
