apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./authorization/disallowed-role-policy/disallowed-role-policy.yaml
- ./authorization/gatekeeper-disalllow-privileged-scc-usage
- ./authorization/default-scc-validation-policy/default-scc-validation-policy.yaml
- ./authorization/role-binding-policy/role-binding-policy.yaml
- ./authorization/role-policy/role-policy.yaml
- ./authorization/gatekeeper-prevent-default-serviceaccount-usage
- ./etcd-security/etcdencryption-policy/etcdencryption-policy.yaml
- ./etcd-security/etcdbackup-policy/etcdbackup-policy.yaml
- ./networking/allow-port-from-namespace-networkpolicy-policy/allow-port-from-namespace-networkpolicy-policy.yaml
- ./networking/deny-all-networkpolicy-policy/deny-all-networkpolicy-policy.yaml
- ./networking/gatekeeper-allow-httpsonly
- ./networking/gatekeeper-disallow-external-ip-services
- ./networking/gatekeeper-disallow-nodeport
- ./resource-exhaustion/gatekeeper-disallow-self-provisioner-policy
- ./resource-exhaustion/limitrange-policy/limitrange-policy.yaml
- ./resource-exhaustion/resourcequota-policy/resourcequota-policy.yaml
- ./resource-exhaustion/gatekeeper-pod-resource-limits
- ./trusted-image-sources/gatekeeper-disallow-image-tags
- ./trusted-image-sources/gatekeeper-disallowed-registries
- ./authentication-user-management/gatekeeper-disallow-anonymous-auth
- ./authentication-user-management/kubeadmin-policy/kubeadmin-policy.yaml
- ./authentication-user-management/gatekeeper-shorten-tokens
- ./authentication-user-management/group-policy/group-policy.yaml
- ./infrastructure-general/gatekeeper-operator-policy
- ./authorization/gatekeeper-disallow-host-namespaces
- ./authorization/gatekeeper-disallow-host-network
- ./authorization/gatekeeper-disallow-cluster-admin
- ./infrastructure-general/certificate-expiry-alert/policy-ocp4-certs.yaml
- ./authorization/gatekeeper-prevent-serviceaccount-automounttoken
- ./authorization/gatekeeper-disallow-scc-runasany
- ./infrastructure-general/check-fips-compliance-policy/check-fips-compliance-policy.yaml
- ./storage/gatekeeper-disallow-emptydir
